drop policy if exists organization_credit_ledger_tenant_isolation_all on organization_credit_ledger;
drop policy if exists organization_credit_balances_tenant_isolation_all on organization_credit_balances;

drop index if exists organization_credit_ledger_org_created_at_idx;
drop index if exists organization_credit_ledger_stripe_event_unique;

drop table if exists organization_credit_ledger;
drop table if exists organization_credit_balances;
